name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, thanks for posting this issue. We will will review it as soon as possible."
        pr-message: "Hello! Thanks for updating Console! We will review your PR as soon as possible."
